PerfectCRM-master/PerfectCRM/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from crm import views
from PerfectCRM import views as main_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crm/', include("crm.urls")),
    url(r'^beeflow/', include("beeflow.urls")),
    url(r'^$', main_views.PortalView.as_view()),
    #url(r'^kingadmin/', include("crm.kingadmin_urls")),
    url(r'^kingadmin/', include("kingadmin.urls")),
    url(r'^stu/', include("student.urls")),
    url(r'^teacher/', include("teacher.urls")),
    url(r'^account/login/', views.acc_login),
    url(r'^account/logout/', views.acc_logout,name='logout'),
]

PerfectCRM-master/beeflow/urls.py
from django.conf.urls import url,include

from beeflow import views


urlpatterns = [

    url(r'^my_application/$', views.my_application,name='my_application'),
    url(r'^flow_detail/(\d+)/$', views.flow_detail,name='flow_detail'),
    url(r'^my_approvals/$', views.my_approvals,name='my_approvals'),
    url(r'^my_approval_records/$', views.my_approval_records,name='my_approval_records'),
    url(r'^flow_examination/(\d+)/$', views.flow_examination,name='flow_examination'),
]

PerfectCRM-master/crm/urls.py
from django.conf.urls import url,include
from crm import  views

urlpatterns = [
    url(r'^$', views.sales_dashboard, name="crm_dashboard"), #销售角色首页
    url(r'^customers/$', views.customers, name="customers"),
    url(r'^customers/change/(\d+)/$', views.customer_change, name="customer_change"),
    url(r'^my_customers/$', views.my_customers, name="my_customers"),
    url(r'^sales_report/$', views.sales_report, name="sales_report"),
    url(r'^enrollment/(\d+)/$', views.enrollment, name="enrollment"),
    url(r'^enrollment/stu/(\d+)/$', views.stu_enrollment, name="stu_enrollment"),
]

PerfectCRM-master/kingadmin/urls.py
from django.conf.urls import url,include
from kingadmin import views

urlpatterns = [

    url(r'^login/$', views.acc_login, name="acc_login"),
    url(r'^logout/$', views.acc_logout, name="acc_logout"),
    url(r'^(\w+)/(\w+)/change/(\d+)/password/$', views.password_reset_form, name='password_reset'),
    url(r'^account/password_reset/$', views.personal_password_reset, name='personal_password_reset'),

    url(r'^$', views.app_index, name="table_index"),  # 显示所有注册的表
    url(r'^(\w+)/$', views.app_tables, name="app_tables"),  # 显示每个app里所有注册的表
    url(r'^(\w+)/(\w+)/$',views.display_table_list,name="table_list"), #显示每个表的数据
    url(r'^(\w+)/(\w+)/add/$', views.table_add, name="table_add"),
    url(r'^(\w+)/(\w+)/change/(\d+)/$', views.table_change, name="table_change"),
    #
    url(r'^(\w+)/(\w+)/delete/(\d+)/$', views.table_del, name="table_del"),


]

PerfectCRM-master/beeflow/models.py
from django.db import models
from  crm import models as crm_models
# Create your models here.



class FlowTemplate(models.Model):
    """流程模版"""
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(blank=True, null=True)
    flow_type_choices = (('FlowVaction', '请假流程'),
                         ('FlowTrip', '出差申请'),
                         ('FlowBecome_Full_Staff', '转正申请'),
                         ('FlowLoan', '借款申请'),
                         )
    flow_type = models.CharField(choices=flow_type_choices, max_length=64)

    def __str__(self):
        return self.name


class Flow(models.Model):
    """流程总表，存储所有流程都会有的公共信息"""
    template = models.ForeignKey(FlowTemplate,on_delete=models.CASCADE)
    started_user = models.ForeignKey(crm_models.UserProfile,verbose_name="流程发起人",on_delete=models.CASCADE)
    content = models.TextField(blank=True,null=True,verbose_name="申请内容")
    in_queue = models.BooleanField(default=True,help_text="只要任务没被人处理，就会一直在queue中")

    date = models.DateTimeField(auto_created=True,auto_now=True)
    def __str__(self):
        return "%s 发起人:%s" %(self.template,self.started_user)

class FlowTrip(models.Model):
    """出差流程"""
    flow = models.ForeignKey("Flow",on_delete=models.CASCADE)
    start_date = models.DateTimeField("开始时间")
    end_date = models.DateTimeField("结束时间")

class FlowLoan(models.Model):
    """借款申请"""
    flow = models.ForeignKey("Flow",on_delete=models.CASCADE)
    usage_choices = ((0,'出差借款'),)
    usage = models.SmallIntegerField(choices=usage_choices,verbose_name="用途")
    amount = models.PositiveIntegerField("借款金额")
    start_date = models.DateTimeField("用款时间")
    end_date = models.DateTimeField("还款时间")


class FlowBecome_Full_Staff(models.Model):
    """转正流程"""
    flow = models.ForeignKey("Flow",on_delete=models.CASCADE)
    probation_start_date = models.DateField("入职日期")
    probation_end_date = models.DateField("转正日期")


class FlowVaction(models.Model):
    """请假流程"""
    flow = models.ForeignKey("Flow",on_delete=models.CASCADE)
    vaction_type_choices  = ((0,'病假'),(1,'年假'),(2,'事假'),(3,'产假'))
    vaction_type = models.SmallIntegerField(choices=vaction_type_choices,default=2)
    start_date = models.DateTimeField("开始时间")
    end_date = models.DateTimeField("结束时间")
    def __str__(self):
        return "%s: %s"%(self.flow,self.vaction_type)


class Step(models.Model):
    """流程的每个环节"""
    flow_template = models.ForeignKey("FlowTemplate",verbose_name="所属流程",on_delete=models.CASCADE)
    name = models.CharField("环节名称",max_length=128)
    description = models.TextField("环节介绍",blank=True,null=True)
    order = models.PositiveSmallIntegerField("环节步骤")
    role = models.ForeignKey("FlowRole",verbose_name="审批角色",on_delete=models.CASCADE)
    is_countersign =  models.BooleanField("会签环节",default=False)
    required_polls = models.PositiveSmallIntegerField("会签最少需同意的人数",blank=True,null=True)

    def __str__(self):
        return "流程:%s 名称:%s 环节:%s" %(self.flow_template,self.name,self.order)

    class Meta:
        unique_together = ("flow_template",'order')


class FlowRecord(models.Model):
    """流程的流转记录"""
    flow = models.ForeignKey("Flow",default=1,on_delete=models.CASCADE)
    step = models.ForeignKey("Step",on_delete=models.CASCADE)
    user = models.ForeignKey(crm_models.UserProfile,verbose_name="审批用户",blank=True,null=True,on_delete=models.CASCADE)
    status_choices = ((0,'同意'),(1,'拒绝'),(2,'需额外审批人审批'),(3,'待处理'))
    status = models.SmallIntegerField(choices=status_choices,verbose_name="审批状态")
    comment = models.TextField(max_length=1024, verbose_name="审批意见")
    extra_parties = models.ManyToManyField(crm_models.UserProfile,verbose_name="额外审批人列表",
                                           related_name="related_parties",
                                           blank=True)
    date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return "%s:%s" %(self.step,self.get_status_display())


class FlowRole(models.Model):
    """流程角色"""
    name = models.CharField(max_length=64,unique=True)
    users = models.ManyToManyField(crm_models.UserProfile,blank=True)
    is_dynamic_role = models.BooleanField(default=False)
    role_lookup_func = models.CharField("查找动态role的函数",max_length=64,blank=True,null=True)

    def __str__(self):
        return self.name

PerfectCRM-master/beeflow/forms.py
#_*_coding:utf-8_*_

from django import forms

class ApprovalForm(forms.Form):
    comment = forms.CharField(label="你的审批意见",widget=forms.Textarea(attrs={'class': "form-control"}))
    status_choices = ((0, '同意'), (1, '拒绝'))
    status = forms.IntegerField(label="审批结果",widget=forms.widgets.Select(choices=status_choices,
                                                                  attrs={'class': "form-control"}))

PerfectCRM-master/beeflow/views.py
from django.shortcuts import render
from beeflow import models
from django.contrib.auth.decorators import login_required
from beeflow import flows
from beeflow import forms

# Create your views here.


@login_required
def my_application(request):



    return render(request,"beeflow/my_application.html")

@login_required
def flow_detail(request,flow_id):
    flow_obj = models.Flow.objects.get(id=flow_id)
    return render(request,"beeflow/flow_detail.html", locals())


def my_approvals(request):
    """flows that needed to be approved by me """

    flow_manager_obj = flows.FlowManger(request)
    queued_flows = flow_manager_obj.get_assigned_to_me_flowlist()

    return render(request,"beeflow/my_approvals.html", locals())

def my_approval_records(request):
    """我的审批记录页"""


    return render(request,"beeflow/my_approval_records.html", locals())


def flow_examination(request,record_id):
    """流程审批页"""
    flow_record_obj = models.FlowRecord.objects.get(id=record_id)
    if request.method == "POST":
        form = forms.ApprovalForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            flow_record_obj.status = form.cleaned_data['status']
            flow_record_obj.user = request.user
            flow_record_obj.comment = form.cleaned_data['comment']
            flow_record_obj.save()
    else:
        form = forms.ApprovalForm()
    return render(request,"beeflow/flow_examination.html",locals())

PerfectCRM-master/templates/beeflow/flow_detail.html
{% extends 'index.html' %}
{% load beeflow_tags %}

{% block page-title-text %}
  流程详情
{% endblock %}

{% block page-content %}

    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">{{ flow_obj }}</h3>
        </div>

        <!-- Striped Table -->
        <!--===================================================-->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>环节</th>
                            <th>审批人</th>

                            <th>审批人意见</th>
                            <th>审批时间</th>
                            <th>审批状态</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for step_record in flow_obj.flowrecord_set.all %}
                        <tr>
                            <td>{{ step_record.step }}</td>
                            <td>{{ step_record.user }}</td>
                            <td>{{ step_record.comment }}</td>
                            <td>{{ step_record.date }}</td>
                            <td>{{ step_record.get_status_display }}</td>

                            <td>{{ obj.date }}</td>
                            <td></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>


{% endblock %}

PerfectCRM-master/templates/beeflow/flow_examination.html
{% extends 'index.html' %}
{% load beeflow_tags %}

{% block page-title-text %}
  审批页
{% endblock %}
{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li><a href="{% url 'my_approvals' %}">我的审批</a></li>
        <li class="active">{{ flow_record_obj.flow }}</li>
    </ol>

{% endblock %}
{% block page-content %}

    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">{{ flow_record_obj.flow }}</h3>
        </div>

        <!-- Striped Table -->
        <!--===================================================-->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    {% get_flow_records flow_record_obj as flow_record_objs %}
                    <thead>
                        <tr>
                            <td>环节</td>
                            <td>环节名称</td>
                            <td>审批人</td>
                            <td>审批意见</td>
                            <td>审批结果</td>
                            <td>审批日期</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for record_obj in flow_record_objs   %}
                        <tr>
                            <td>{{ record_obj.step.order }}</td>
                            <td>{{ record_obj.step.name }}</td>
                            <td>{{ record_obj.user }}</td>
                            <td>{{ record_obj.comment }}</td>
                            <td>{{ record_obj.get_status_display }}</td>
                            <td>{% if record_obj.user %}
                                    {{ record_obj.date }}
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>

                </table>
            </div>

            <form class="form" method="post">{% csrf_token %}
                <div class="row">
                    <div class="col-md-12">
                    <h3>当前环节: {{ flow_record_obj}}</h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        {{ form.comment.label }}
                        {{ form.comment }}
                    </div>
                    <div class="col-md-4" style="margin-top:20px">
                            {{ form.status.label }}
                            {{ form.status }}

                    </div>
                    <div class="col-lg-12" style="margin-top:20px">
                            <input type="submit" class="btn btn-success">
                    </div>


                </div>

            </form>

        </div>


    </div>


{% endblock %}

PerfectCRM-master/templates/beeflow/my_application.html
{% extends 'index.html' %}
{% load beeflow_tags %}

{% block page-title-text %}
  我的流程申请
{% endblock %}

{% block page-content %}

    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">我的申请</h3>
        </div>

        <!-- Striped Table -->
        <!--===================================================-->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>流程</th>
                            <th>内容</th>
                            <th>发起时间</th>
                            <th>目前状态</th>
                        </tr>
                    </thead>
                {{ request.user.flow_set.all }}
                    <tbody>
                        {% for obj in request.user.flow_set.all %}
                        <tr>
                            <td>{{ obj.id }}</td>
                            <td>{{ obj.template.name }}</td>
                            <td>{{ obj.content }}</td>
                            <td>{{ obj.date }}</td>
                            <td><a class="btn-link" href="{% url 'flow_detail' obj.id %}">{% get_flow_status obj  %}</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>


{% endblock %}

PerfectCRM-master/templates/beeflow/my_approval_records.html
{% extends 'index.html' %}
{% load beeflow_tags %}

{% block page-title-text %}
  我的审批记录
{% endblock %}

{% block page-content %}

    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">{{ flow_obj }}</h3>
        </div>

        <!-- Striped Table -->
        <!--===================================================-->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>流程</th>
                            <th>发起时间</th>
                            <th>申请人</th>
                            <th>申请内容</th>
                            <th>上一环节审批人</th>
                            <th>上一环节审批意见</th>
                            <th>上一环节审批结果</th>
                            <th>上一环节审批时间</th>
                            <th>当前状态</th>
                            <th>审批</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>


{% endblock %}

PerfectCRM-master/templates/beeflow/my_approvals.html
{% extends 'index.html' %}
{% load beeflow_tags %}

{% block page-title-text %}
  需要我审批的流程
{% endblock %}

{% block page-content %}

    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">{{ flow_obj }}</h3>
        </div>

        <!-- Striped Table -->
        <!--===================================================-->
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>流程</th>
                            <th>发起时间</th>
                            <th>申请人</th>
                            <th>申请内容</th>
                            <th>上一环节审批人</th>
                            <th>上一环节审批意见</th>
                            <th>上一环节审批结果</th>
                            <th>上一环节审批时间</th>
                            <th>当前状态</th>
                            <th>审批</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if queued_flows %}
                            {% for flow_record in queued_flows  %}
                                {% get_last_step_obj flow_record as last_step_record_obj %}

                                <tr>
                                    <td>{{ flow_record.flow }}</td>
                                    <td>{{ flow_record.flow.date }}</td>
                                    <td>{{ flow_record.flow.started_user }}</td>
                                    <td >{{ flow_record.flow.content }}</td>
                                    <td class="btn-info">{{ last_step_record_obj.user }}</td>
                                    <td class="btn-info">{{ last_step_record_obj.comment }}</td>
                                    <td class="btn-info">{{ last_step_record_obj.get_status_display }}</td>
                                    <td class="btn-info">{{ last_step_record_obj.date }}</td>

                                    <td>{{ flow_record.get_status_display }}</td>

                                    <td><a href="{% url 'flow_examination' flow_record.id %}"><i style="cursor: pointer;color: #1c94c4" class="fa fa-pencil-square-o " aria-hidden="true"></i></a></td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr><td style="text-align: center" colspan="10"><span style="font-size: 20px">当前无需要审批的流程!</span></td></tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>


{% endblock %}