Luffymonitor/Luffymonitor/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from web import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index,name='index'),
    url(r'^api/', include("monitor.api_urls")),
    url(r'^monitor/db_list$', views.db_list,name='db_list'),
    url(r'^monitor/tablespace/$', views.tablespace,name='tablespace'),
    url(r'^monitor/items$', views.monitor_items,name='monitor_items'),
    url(r'^report/', views.report, name='report'),
    url(r'^detail/', views.tbs_detail, name='tbs_detail'),
    url(r'^modal/', views.modal, name='modal')
]

Luffymonitor/web/models.py
from django.db import models
from django.contrib.auth.models import User
import django.utils.timezone as timezone
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser,PermissionsMixin
)

# Create your models here.

class IDC(models.Model):
    '''机房表'''
    name = models.CharField(max_length=64,unique=True,verbose_name='机房')

    def __str__(self):
        return self.name

class Business(models.Model):
    '''应用厂商表'''
    name = models.CharField(max_length=64,unique=True,verbose_name='厂商')

    def __str__(self):
        return self.name

class AppCompany(models.Model):
    """应用厂商表"""
    name = models.CharField(max_length=64, unique=True,verbose_name='业务系统')

    def __str__(self):
        return self.name

class Host(models.Model):
    """主机列表"""
    hostname = models.CharField(max_length=64,verbose_name="主机名")
    instance_name = models.CharField(max_length=64,verbose_name="实例名")
    ip_addr = models.GenericIPAddressField(unique=True,verbose_name="IP地址")
    port = models.PositiveSmallIntegerField(default=22,verbose_name="端口号")
    connect_type_choices = ((0,'ssh'),(1,'telnet'),(2,'snmp'))
    host_conn_type = models.SmallIntegerField(choices=connect_type_choices,default=0,verbose_name="主机连接方式")
    db_port = models.PositiveSmallIntegerField(default=1521,null=True,verbose_name="DB端口号")
    username = models.CharField(max_length=64,verbose_name="用户名")
    db_username = models.CharField(max_length=64)
    password = models.CharField(max_length=128, blank=True, null=True)
    db_password = models.CharField(max_length=128, blank=True, null=True)
    database_type_choices = ((0, 'oracle 10g'), (1, 'oracle 11g'), (2, 'oracle 12c'), (3, 'mysql'))
    database_type = models.SmallIntegerField(choices=database_type_choices,default=0,verbose_name="数据库类型")
    os_type_choices = ((0,'Linux'),(1,'windows'),(2,'AIX'),(3,'other'))
    os_type = models.SmallIntegerField(choices=os_type_choices,default=0,verbose_name="OS类型")
    idc = models.ForeignKey("IDC",on_delete=models.CASCADE,verbose_name="机房")
    business = models.ForeignKey("Business",on_delete=models.CASCADE,verbose_name="业务系统名称")
    appcompany = models.ForeignKey("AppCompany",on_delete=models.CASCADE,verbose_name="厂商")
    templates = models.ManyToManyField("Template", blank=True)  # A D E

    enabled = models.BooleanField(default=True)
    is_database = models.BooleanField(default=True)
    comment = models.CharField(max_length=128, blank=True, null=True,verbose_name="备注")


    def __str__(self):
        return self.ip_addr


class Tablespace(models.Model):
    name = models.CharField(max_length=64,blank=True)
    total_size = models.CharField(max_length=64,blank=True)
    free_size = models.CharField(max_length=64,blank=True)
    used_size = models.CharField(max_length=64,blank=True)
    time = models.TimeField('时间',auto_now_add=True)
    host = models.ForeignKey('Host',on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Service(models.Model):
    '''服务列表，一个服务对应多个指标，'''
    name = models.CharField(u'服务名称',max_length=64,unique=True)
    interval = models.IntegerField(u'监控间隔',default=60)
    plugin_name = models.CharField(u'插件名',max_length=64,default='n/a')
    has_sub_service = models.BooleanField(default=False,help_text=u"如果一个服务还有独立的子服务 ,选择这个,比如 网卡服务有多个独立的子网卡") #如果一个服务还有独立的子服务 ,选择这个,比如 网卡服务有多个独立的子网卡
    memo = models.CharField(u"备注",max_length=128,blank=True,null=True)

    def __str__(self):
        return self.name


class Template(models.Model):
    name = models.CharField(u'模版名称',max_length=64,unique=True)
    services = models.ManyToManyField('Service',verbose_name=u"服务列表")
    #triggers = models.ManyToManyField('Trigger',verbose_name=u"触发器列表",blank=True)
    def __str__(self):
        return self.name


class CpuInfo(models.Model):
    ip = models.CharField(max_length=64,blank=True,verbose_name=u"IP地址")
    user = models.DecimalField(max_digits=5, decimal_places=2,null=True,verbose_name=u"用户使用率")
    nice = models.DecimalField(max_digits=5, decimal_places=2,null=True,verbose_name=u"NICE")
    system  = models.DecimalField(max_digits=5, decimal_places=2,null=True,verbose_name=u"系统使用率")
    idle = models.DecimalField(max_digits=5, decimal_places=2,null=True,verbose_name=u"空闲率")
    time = models.CharField(max_length=64,blank=True,null=True,verbose_name=u"采集时间")
    status = models.CharField(max_length=6,blank=True,verbose_name=u"状态")
    host = models.ForeignKey('Host',null=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.ip

class MemInfo(models.Model):
    ip = models.CharField(max_length=64,blank=True,verbose_name=u"IP地址")
    MemTotal = models.DecimalField(max_digits=10, decimal_places=2,null=True,verbose_name=u"总内存(Kb)")
    MemFree = models.DecimalField(max_digits=10, decimal_places=2,null=True,verbose_name=u"未分配内存(Kb)")
    Buffers  = models.DecimalField(max_digits=10, decimal_places=2,null=True,verbose_name=u"Buffers(Kb)")
    Cached = models.DecimalField(max_digits=10, decimal_places=2,null=True,verbose_name=u"Cached(Kb)")
    SwapTotal = models.DecimalField(max_digits=10, decimal_places=2,null=True,verbose_name=u"总Swap(Kb)")
    SwapFree = models.DecimalField(max_digits=10, decimal_places=2,null=True,verbose_name=u"空闲swap(Kb)")
    SwapUsage_p = models.DecimalField(max_digits=10, decimal_places=2,null=True,verbose_name=u"swap使用率")
    SwapUsage = models.DecimalField(max_digits=10, decimal_places=2,null=True,verbose_name=u"已用swap(Kb)")
    MemUsage_p = models.DecimalField(max_digits=10, decimal_places=2,null=True,verbose_name=u"内存使用率")
    MemUsage = models.DecimalField(max_digits=10, decimal_places=2,null=True,verbose_name=u"已分配内存(Kb)")
    time = models.CharField(max_length=64,blank=True,null=True,verbose_name=u"采集时间")
    status = models.CharField(max_length=6,blank=True,verbose_name=u"状态")

    host = models.ForeignKey('Host',null=True,on_delete=models.CASCADE)

class Filesystem(models.Model):
    ip = models.CharField(max_length=64, blank=True, verbose_name=u"IP地址")
    mount_point = models.CharField(max_length=64,blank=True,verbose_name=u"挂载点")
    Total_size = models.PositiveIntegerField(verbose_name=u'总大小')
    used_size = models.PositiveIntegerField(verbose_name=u'已用')
    avail_size = models.PositiveIntegerField(verbose_name=u'剩余')
    time = models.CharField(max_length=64, blank=True, null=True, verbose_name=u"采集时间")
    status = models.CharField(max_length=6,blank=True,verbose_name=u"状态")

    host = models.ForeignKey('Host',null=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.mount_point


class LoadInfo(models.Model):
    ip = models.CharField(max_length=64,blank=True,verbose_name=u"IP地址")
    runtime = models.CharField(max_length=64,blank=True,verbose_name=u"IP地址")
    users = models.CharField(max_length=64,blank=True,verbose_name=u"IP地址")
    load1  = models.DecimalField(max_digits=5, decimal_places=2,null=True,verbose_name=u"Buffers(Kb)")
    load5  = models.DecimalField(max_digits=5, decimal_places=2,null=True,verbose_name=u"Buffers(Kb)")
    load15  = models.DecimalField(max_digits=5, decimal_places=2,null=True,verbose_name=u"Buffers(Kb)")

    time = models.CharField(max_length=64,blank=True,null=True,verbose_name=u"采集时间")
    status = models.CharField(max_length=6,blank=True,verbose_name=u"状态")

    host = models.ForeignKey('Host',null=True,on_delete=models.CASCADE)

Luffymonitor/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login page | AutoOps - Responsive admin template.</title>


    <!--STYLESHEET-->
    <!--=================================================-->

    <!--Open Sans Font [ OPTIONAL ] -->
     <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;subset=latin" rel="stylesheet">


    <!--Bootstrap Stylesheet [ REQUIRED ]-->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">


    <!--Nifty Stylesheet [ REQUIRED ]-->
    <link href="/static/css/nifty.min.css" rel="stylesheet">


    <!--Font Awesome [ OPTIONAL ]-->
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">


    <!--Demo [ DEMONSTRATION ]-->
    <link href="/static/css/nifty-demo.min.css" rel="stylesheet">




    <!--SCRIPT-->
    <!--=================================================-->

    <!--Page Load Progress Bar [ OPTIONAL ]-->
    <link href="/static/plugins/pace/pace.min.css" rel="stylesheet">
    <script src="/static/plugins/pace/pace.min.js"></script>



	<!--

	REQUIRED
	You must include this in your project.

	RECOMMENDED
	This category must be included but you may modify which plugins or components which should be included in your project.

	OPTIONAL
	Optional plugins. You may choose whether to include it in your project or not.

	DEMONSTRATION
	This is to be removed, used for demonstration purposes only. This category must not be included in your project.

	SAMPLE
	Some script samples which explain how to initialize plugins or components. This category should not be included in your project.


	Detailed information and more samples can be found in the document.

	-->


</head>

<!--TIPS-->
<!--You may remove all ID or Class names which contain "demo-", they are only used for demonstration. -->

<body>

    {% block body %}body content{% endblock %}

	<!--===================================================-->
	<!-- END OF CONTAINER -->



	<!--JAVASCRIPT-->
	<!--=================================================-->

	<!--jQuery [ REQUIRED ]-->
	<script src="/static/js/jquery-2.1.1.min.js"></script>


	<!--BootstrapJS [ RECOMMENDED ]-->
	<script src="/static/js/bootstrap.min.js"></script>


	<!--Fast Click [ OPTIONAL ]-->
	<script src="/static/plugins/fast-click/fastclick.min.js"></script>


	<!--Nifty Admin [ RECOMMENDED ]-->
	<script src="/static/js/nifty.min.js"></script>


	<!--Background Image [ DEMONSTRATION ]-->
	<script src="/static/js/demo/bg-images.js"></script>


	<!--

	REQUIRED
	You must include this in your project.

	RECOMMENDED
	This category must be included but you may modify which plugins or components which should be included in your project.

	OPTIONAL
	Optional plugins. You may choose whether to include it in your project or not.

	DEMONSTRATION
	This is to be removed, used for demonstration purposes only. This category must not be included in your project.

	SAMPLE
	Some script samples which explain how to initialize plugins or components. This category should not be included in your project.


	Detailed information and more samples can be found in the document.

	-->
		
	<!--===================================================-->
	<!-- END OF CONTAINER -->



	<!--JAVASCRIPT-->
	<!--=================================================-->

	<!--jQuery [ REQUIRED ]-->
	<script src="/static/js/jquery-2.1.1.min.js"></script>


	<!--BootstrapJS [ RECOMMENDED ]-->
	<script src="/static/js/bootstrap.min.js"></script>


	<!--Fast Click [ OPTIONAL ]-->
	<script src="/static/plugins/fast-click/fastclick.min.js"></script>


	<!--Nifty Admin [ RECOMMENDED ]-->
	<script src="/static/js/nifty.min.js"></script>


	<!--Background Image [ DEMONSTRATION ]-->
	<script src="/static/js/bg-images.js"></script>


	<!--

	REQUIRED
	You must include this in your project.

	RECOMMENDED
	This category must be included but you may modify which plugins or components which should be included in your project.

	OPTIONAL
	Optional plugins. You may choose whether to include it in your project or not.

	DEMONSTRATION
	This is to be removed, used for demonstration purposes only. This category must not be included in your project.

	SAMPLE
	Some script samples which explain how to initialize plugins or components. This category should not be included in your project.


	Detailed information and more samples can be found in the document.

	-->


</body>
</html>

Luffymonitor/templates/host_list_component.html
<div class="col-lg-4" style="width: 230px;float: left;">
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">主机列表</h3>
        </div>
        <div class="panel-body">
                <div class="list-group bord-no">
                    <a onclick="HostListDisplayToggle(this)" class="list-group-item " href="#">
                        <input type="checkbox" onclick="SelectGroup(this)">
                        全部主机
                        <span class="badge badge-primary">{{ hosts.count }}</span>
                    </a>
                    <ol class="hide">
                        {% for bind_host in hosts %}
                            <li><input type="checkbox"  select_host="true" value="{{ bind_host.id }}">{{ bind_host.ip_addr }}</li>
                        {% endfor %}
                    </ol>



                    {% for bus in business.select_related %}

                        <a onclick="HostListDisplayToggle(this)" class="list-group-item " href="#">
                            <input type="checkbox" onclick="SelectGroup(this)">
                            {{ bus.name }}
                            <span class="badge badge-primary">{{ bus.host_set.count }}</span>
                        </a>
                        <ol class="hide">
                            {% for host in bus.host_set.all %}
                                <li><input type="checkbox"  select_host="true" value="{{ host.id }}">{{ host.ip_addr }}</li>
                            {% endfor %}
                        </ol>


                    {% endfor %}
                </div>
        </div>
    </div>

</div>

Luffymonitor/templates/host_list_js_component.html
<script>




    function HostListDisplayToggle(ele) {

        $(ele).next().toggleClass("hide");


    }

    function SelectGroup(ele) {

        $(ele).parent().next().find("input").prop("checked",$(ele).prop("checked"))

    }


{#    function PostTask(ele,task_type) {#}
{##}
{#        var selected_host_ids  = [];#}
{##}
{#        $("input[select_host]:checked").each(function () {#}
{#            selected_host_ids.push( $(this).val()  );#}
{#        })       //取得选中主机的id#}
{##}
{#        console.log(selected_host_ids)#}
{#        if (selected_host_ids.length == 0){#}
{#            alert("必须选择主机!")#}
{#            return false#}
{#        }#}
{##}
{#        if (task_type == "cmd"){#}
{#            var cmd_text = $("#cmd_text").val().trim();    // 取得输入的命令#}
{##}
{#            if (cmd_text.length == 0){#}
{##}
{#                alert("必须输入要执行的命令!")#}
{#                return false#}
{#            }#}
{##}
{#            var task_arguments = {#}
{#                'selected_host_ids' : selected_host_ids,#}
{#                'task_type':0 ,//cmd#}
{#                'cmd': cmd_text,#}
{##}
{#            }  //选中主机的id、任务类型、命令存储成一个字典#}
{##}
{#        }else {#}
{##}
{#            var file_transfer_type = $("select[name='file_transfer_type']").val()#}
{#            var local_file_path = $("#local_file_path").val().trim()#}
{#            var remote_file_path = $("#remote_file_path").val().trim()#}
{#            if (file_transfer_type == "send"){#}
{#                if (local_file_path.length == 0){#}
{#                    alert("必须输入本地文件路径！")#}
{#                    return false#}
{#                }#}
{##}
{#            }#}
{##}
{#            if (remote_file_path.length == 0){#}
{#                    alert("必须输入远程文件路径！")#}
{#                    return false#}
{#            }#}
{##}
{#            var task_arguments = {#}
{#                'selected_host_ids' : selected_host_ids,#}
{#                'task_type':1 ,//file_transfer#}
{#                'file_transfer_type': file_transfer_type,#}
{#                'local_file_path':local_file_path,#}
{#                'remote_file_path':remote_file_path#}
{##}
{#            }#}
{##}
{#        }#}
{##}
{##}
{##}
{##}
{#        //再此任务执行完成前，不允许再提交新任务#}
{#        $(ele).addClass("disabled")#}
{#        //提交新任务之前清空任务结果面版#}
{#        $("#task_result_container").empty();#}
{##}
{##}
{#        $.post("{%  url 'multitask' %}"  , {'task_data':JSON.stringify(task_arguments),'csrfmiddlewaretoken':$("input[name='csrfmiddlewaretoken']").val() },function(callback){#}
{##}
{#            console.log('PostTask:',callback);#}
{##}
{#            var callback = JSON.parse(callback);#}
{#            $.each(callback.selected_hosts,function (index,ele) {#}
{#                var li_ele = "<li bind_host_id='"+ ele['id'] +"'>Host:" + ele.bind_host__host__hostname + "(" +ele.bind_host__host__ip_addr +")----------------<span></span></li><pre>sdff</pre>" ;#}
{#                $("#task_result_container").append(li_ele);#}
{##}
{#            })#}
{##}
{##}
{##}
{#             //去后端定时拿结果#}
{#			var timer_counter = 0#}
{#            get_result_timer = setInterval(function () {#}
{##}
{#                    GetTaskResult(callback.task_id);#}
{##}
{#					//if (timer_counter < 10){ //还可以继续运行#}
{#					if (timer_counter < callback.timeout){ //还可以继续运行#}
{#						timer_counter +=2;#}
{#					}else{#}
{#						clearInterval(get_result_timer);#}
{#						console.log('task is timed out')#}
{##}
{#                     $.niftyNoty({#}
{#                            type: "warning",#}
{#                            container : "floating",#}
{#                            title : "You have've got 30 Messages",#}
{#                            message : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",#}
{#                            closeBtn : true,#}
{#                            timer : 25000#}
{#                        });#}
{#					}#}
{##}
{##}
{##}
{#                },2000);#}
{##}
{#        });//end post#}
{##}
{##}
{##}
{#    }#}
{#	    function  GetTaskResult(task_id) {#}
{##}
{#			$.getJSON( "{% url 'task_result'  %}" ,{'task_id':task_id},function(callback){#}
{##}
{#           console.log( 'GetTaskResult:',callback);#}
{#           var all_task_done = true;#}
{#           var finished_task_counter = 0#}
{#           $.each(callback,function (index,ele) {#}
{#               var li_ele = $("li[bind_host_id='"+  ele['id'] +"']");#}
{#               li_ele.next().text(ele['result']);    // 找到li的下一个标签并修改标签内容#}
{#               $(li_ele.children()[0]).text(ele.status);#}
{#               if ( ele.status == 2 ){#}
{#                   all_task_done = false; //有任务未完成#}
{#               }#}
{#               else {#}
{#                   //执行完成#}
{#                   finished_task_counter += 1#}
{#               }#}
{##}
{##}
{#           })#}
{##}
{#           if (all_task_done){#}
{#                // 代表所有任务执行完成#}
{#               clearInterval(get_result_timer);#}
{#               $("#post_task_btn").removeClass("disabled");#}
{#               $.niftyNoty({#}
{#                    type: "success",#}
{#                    container : "floating",#}
{#                    title : "You have've got 30 Messages",#}
{#                    message : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit",#}
{#                    closeBtn : false,#}
{#                    timer : 5000#}
{#                });#}
{#           }#}
{#            //进度条实现#}
{#           var finished_percent = finished_task_counter / callback.length * 100#}
{#           $("#task_process").parent().removeClass("hide");#}
{#           $("#task_process").css("width",finished_percent+"%").text(finished_percent+"%")#}
{##}
{#        });//end getJSON#}
{#    }#}

</script>

Luffymonitor/templates/modals1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>模态框</title>

    <!--Bootstrap Stylesheet [ REQUIRED ]-->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <!--Font Awesome [ OPTIONAL ]-->
    <link href="/static/css/bootstrap-theme.css" rel="stylesheet">
    <style>
        .modal.resText {
                top: 50%;
                left: 30%;
                width: 1050px;
                height: 450px;
                margin-left: -256px;
                margin-top: -250px;
            }
    </style>
</head>
<body>
    <!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>

<!-- Modal -->
    <div class="modal resText fade " id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>
    <script src="/static/jquery-2.1.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
</body>


</html>

Luffymonitor/templates/monitor_items.html
{% extends 'index.html' %}


{% block page-title %}监控{% endblock %}

{% block page-content %}
    {% csrf_token %}

<div class="row">

    {% include 'host_list_component.html' %}

    <div class="panel panel-primary" style="margin-left: 235px;">

        <!--Panel heading-->
        <div class="panel-heading">
            <div class="panel-control">

                <!--Nav tabs-->
                <ul class="nav nav-tabs">
                    <li id="myTab" class="active"><a data-toggle="tab" href="#tablespace" onclick="getItemsValues()">表空间</a>
                    </li>
                    <li><a data-toggle="tab" href="#demo-tabs-box-2">等待事件</a>
                    </li>
                </ul>

            </div>
            <h3 class="panel-title">监控项</h3>
        </div>

        <!--Panel body-->
        <div class="panel-body" style="padding-bottom: 20px;" >

            <!--Tabs content-->
            <div class="tab-content">
                <div id="tablespace" class="tab-pane fade in active" >

                </div>

                <div id="demo-tabs-box-2" class="tab-pane fade">
                    <h4 class="text-thin">Second Tab Content</h4>
                    <p>Duis autem vel eum iriure dolor in hendrerit in vulputate.</p>
                </div>
            </div>
        </div>
    </div>

</div>

<script src="/static/echarts.min.js" charset="utf-8" type="text/javascript"></script>
<script src="/static/jquery-2.1.1.min.js" charset="utf-8" type="text/javascript"></script>
<script src="/static/js/bootstrap.min.js"></script>
{% include 'host_list_js_component.html' %}
<script type="text/javascript">

    function getItemsValues() {
        var selected_host_ids  = [];

        $("input[select_host]:checked").each(function () {
            selected_host_ids.push($(this).val());
        })
        var task_arguments = {
            'selected_host_ids': selected_host_ids
        }
        hosts = JSON.stringify((task_arguments))
{#        $.post("{%  url 'tablespace' %}"  , {'hosts': JSON.stringify((task_arguments))})#}

        $("div").remove("#tablespace div");
        $("#tablespace").find('iframe').remove()
        var iframe = document.createElement('iframe')
        iframe.setAttribute("src","../monitor/tablespace?host_ids="+hosts)
        iframe.setAttribute("style","width:950px;height:425px")
        iframe.setAttribute("frameborder","0")
        $("#tablespace").append(iframe)
        console.log(selected_host_ids)

    }

</script>

{% endblock %}

Luffymonitor/templates/tablespace.html
{% load models_handle %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>表空间</title>
</head>
<body>
</body>
<script src="/static/echarts.min.js" charset="utf-8" type="text/javascript"></script>
<script src="/static/jquery-2.1.1.min.js" charset="utf-8" type="text/javascript"></script>
<script src="/static/js/bootstrap.min.js"></script>
{#{% include 'host_list_js_component.html' %}#}
<script type="text/javascript">
    function adddiv() {
        var hosts = [{% for h in hosts %}'{{ h.host_id }}',{% endfor %}];
        console.log(hosts)
        hosts.forEach(function (host) {
            $("body").prepend('<div id="host'+host+'"'+' style="width:400px;height:200px;left:1%;float: left"></div>')
            name = $("div").attr('id')
            echart(name,host)
        })
    }

    // 使用
    function echart(name,host) {
        console.log(name,host)
        // 基于准备好的dom，初始化echarts图表
        var myChart = echarts.init(document.getElementById(name));
        //过滤数组
        var tablespace = {% tablespace_part %}
        var result = []
        //遍历数组，并根据条件形成新的数组
        for(var i=0,len=tablespace.length;i<len;i++){
            var a = tablespace[i][4]
            if (a==host){
                result.push(tablespace[i])
            }
        }
        console.log("RESULT:",result)

        var tbs_name = result.map(function(value){return value[0]})
        var tbs_used = result.map(function(value){return value[3]})
        var tbs_free = result.map(function(value){return value[2]})
        var ip_addr = result[0][5]
        var option = {
            title: {
                text: '表空间',
                subtext: "IP地址：" + ip_addr
            },
            label: {
                textStyle: {
                    color: 'rgba(255, 255, 255, 0.3)'
                }
            },
            tooltip: {
                trigger: 'axis',
                axisPointer: {            // 坐标轴指示器，坐标轴触发有效
                    type: 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
                }
            },
            legend: {
                data: ['已用（MB）', '剩余(MB)']
            },
            grid: {
                left: '3%',
                right: '4%',
                bottom: '3%',
                containLabel: true
            },
            xAxis: [
                {
                    type: 'category',
                    data: tbs_name
                }
            ],
            yAxis: [
                {
                    type: 'value',
                    axisLabel: {
                        formatter: '{value} MB'
                    }
                }
            ],
            series: [
                {
                    name: '已用（MB）',
                    type: 'bar',
                    stack: '表空间',
                    data: tbs_used
                },
                {
                    name: '剩余(MB)',
                    type: 'bar',
                    stack: '表空间',
                    data: tbs_free
                },


            ]
        };
        // 为echarts对象加载数据
        myChart.setOption(option);
    }
    adddiv()


</script>
</html>